import Head from 'next/head';
import Brand from '@/components/Brand';
import CardEvent from '@/components/CardEvent';
import Stories from '@/components/Stories';
import Statistics from '@/components/Statistics';
import Header from '@/components/Header';
import { getData } from '@/utils/fetchData';
import Footer from '@/components/Footer';

export default function Home({ data }) {
  console.log(data);
  return (
    <>
      <Head>
        <title>Semina || Landing Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <Brand />
      <CardEvent data={data} title='Featured Events' subTitle='Grow Today' />
      <Stories />
      <Statistics />
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  const req = await getData('/api/v1/events');
  const res = req.data;

  return {
    props: { data: res },
  };
}
